baseURL = 'https://leomindwalk.xyz'
languageCode = 'en-us'
defaultContentLanguage = "en"
enableRobotsTXT = true
title = ''
theme='gokarna-hugo'

[module]
    [[module.mounts]]
        source = "content"
        target = "content"

[params]
    subtitle = 'Developer & Thinker'
    
    github = "https://github.com/dionysusliu"
    
    linkedin = "https://www.linkedin.com/in/chuangliuleo/"
    
    email = "chuangliu0815@gmail.com"

    customCSS = ["css/custom.css"]

    avatarURL = "/images/avatar-laguna-stars.jpg"

    favicon = "favicon-32x32.png"

    avatarSize = "size-l"

    dateFormat = "August 15, 2001"

    description = "Obstacle is the way."

    metaKeywords = ["blog", "gokarna", "hugo"]

    socialIcons = [
        {name = "gmail", url = "mailto:chuangliu0815@gmail.com"},
        {name = "linkedin", url = "https://www.linkedin.com/in/chuangliuleo/"},
        {name = "github", url = "https://github.com/dionysusliu"},
        {name = "wechat", url = "/wechat/"},
        {name = "reddit", url = "https://www.reddit.com/user/Leo_mindwalker/"},
        {name = "steam-fill", url = "https://steamcommunity.com/profiles/76561198410627413/"},
    ]

    relativeURLs = true
    
    canonifyURLs = true

[[menu.main]]
    name = "Home"
    url = "/"
    pre = "<span data-feather='home'></span>"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[[menu.main]]
    identifier = "github"
    url = "https://github.com/dionysusliu"
    weight = 5
    pre = "<span data-feather='github'></span>"
    post = ""